## CSV Files

In [11]:
import csv

In [12]:
with open('test.csv') as f:
    data = csv.reader(f)
    for row in data:
        print(row)

['Programming language', ' Designed by', ' Appeared', ' Extension']
['Python', ' Guido van Rossum', ' 1991', ' .py']
['Java', ' James Gosling', ' 1995', ' .java']
['C++', ' Bjarne Stroustrup', ' 1983', ' .cpp']


In [17]:
reader = csv.DictReader(open('test.csv', 'rt'))
for row in reader:
    print(row)

{'Programming language': 'Go', 'Designed by': 'Davasam Karthikeya', 'Appeared': '2005', 'Extension': '.go'}
{'Programming language': 'Python', 'Designed by': 'Guido van Rossum', 'Appeared': '1991', 'Extension': '.py'}
{'Programming language': 'Java', 'Designed by': 'James Gosling', 'Appeared': '1995', 'Extension': '.java'}
{'Programming language': 'C++', 'Designed by': 'Bjarne Stroustrup', 'Appeared': '1983', 'Extension': '.cpp'}


In [16]:
with open('test.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerow(['Programming language', 'Designed by', 'Appeared', 'Extension'])
    writer.writerow(['Go', 'Davasam Karthikeya', '2005', '.go'])
    writer.writerow(['Python', 'Guido van Rossum', '1991', '.py'])
    writer.writerow(['Java', 'James Gosling', '1995', '.java'])
    writer.writerow(['C++', 'Bjarne Stroustrup', '1983', '.cpp'])

## Pandas

In [19]:
import pandas as pd

In [23]:
df = pd.read_csv('test.csv')

In [24]:
df

Programming language         Designed by  Appeared Extension
0                   Go  Davasam Karthikeya      2005       .go
1               Python    Guido van Rossum      1991       .py
2                 Java       James Gosling      1995     .java
3                  C++   Bjarne Stroustrup      1983      .cpp

## Numpy

In [35]:
import numpy as np

In [37]:
arr = np.arange(15).reshape(3, 5)

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
print('ndim: ',arr.ndim)
print('shape: ', arr.shape)
print('size: ', arr.size)
print('dtype: ', arr.dtype)
print('itemsize: ', arr.itemsize)
print('data: ', arr.data)

ndim:  2
shape:  (3, 5)
size:  15
dtype:  int64
itemsize:  8
data:  <memory at 0x7f74b1fb1cb0>


In [48]:
py_arr = [[1,2,3],[4,5,6]]
arr = np.array(py_arr)
arr, py_arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 [[1, 2, 3], [4, 5, 6]])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.empty((5,2))

array([[1.4115e-320, 7.7771e-320],
       [5.3359e-321, 9.5572e-320],
       [2.8547e-320, 2.8547e-320],
       [9.5572e-320, 5.3359e-321],
       [7.7771e-320, 1.4115e-320]])

In [56]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [58]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])